name: ${project.name}
version: ${project.version}
main: com.lenis0012.bukkit.loginsecurity.LoginSecurity
api-version: ${api.plugin.version}
author: lenis0012
description: 'The #1 Auth plugin'
softdepend: [ProtocolLib]
commands:
  login:
    description: Login with your account.
    usage: /login <password>
  register:
    description: Set a password for your account.
    usage: /register <password>
  changepassword:
    description: Change your account password.
    aliases: [changepass]
    usage: /changepass <old pass> <new pass>
  logout:
    description: Log out of your account.
    usage: /logout
  unregister:
    description: Unregister your account.
    usage: /unregister <current password>
  lac:
    description: LoginSecurity Admin command.
    usage: /lac