name: LoginSecurity
version: 2.0.3
main: com.lenis0012.bukkit.ls.LoginSecurity
author: lenis0012
description: The #1 Auth plugin
softdepend: [xAuth]
commands:
  login:
    description: Login with your account.
    usage: /login <username>
  register:
    description: Set a password for your account.
    usage: /register <username>
  changepass:
    description: Change the password for your account.
    usage: /changeuser <old> <new>
  rmpass:
    description: Remove your password.
    usage: /rmuser <username>
  logout:
    description: Logout
    usage: /logout
